{{- if .Values.engine.enabled }}
{{ $config := .Values.engine.config  | default dict -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-defaults
  namespace: {{ .Values.engine.namespace }}
data:
  default-service-account: {{ $config.defaultServiceAccount | default "build-bot-sa" | quote }}
  default-timeout-minutes: {{ $config.defaultTimeoutMinutes | default "60" | quote }}
  {{ if hasKey .Values.engine.config "defaultPodTemplate" -}}
  default-pod-template: |
    {{- .Values.engine.config.defaultPodTemplate | nindent 4 }}
  {{end}}

{{ end }}
