{{ if .Values.serviceAccount.create }}

# this is default sa under which we run our EventListeners
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}

{{- end }} # if apps
