{{ if .Values.apps }}
{{ if .Values.serviceAccount.create }}
# this is default sa under which we run our EventListeners
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ include "tekton-apps.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
# Required bindings for eventlistener, see more here:
# https://tekton.dev/docs/triggers/eventlisteners/#specifying-the-kubernetes-service-account
# kind: RoleBinding
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: {{ include "tekton-apps.serviceAccountName" . }}
#   namespace: {{ $.Release.Namespace }}
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role
#   name: tekton-triggers-eventlistener-roles
# subjects:
# - kind: ServiceAccount
#   name: {{ include "tekton-apps.serviceAccountName" . }}
#   namespace: {{ $.Release.Namespace }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "tekton-apps.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
subjects:
- kind: ServiceAccount
  name: {{ include "tekton-apps.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "tekton-apps.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
subjects:
- kind: ServiceAccount
  name: {{ include "tekton-apps.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
{{- end }} # if serviceAccount.create
{{- end }} # iff apps
