{{ if .Values.apps }}
# this is default sa under which we run our EventListener
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
---

{{- range $project := .Values.apps }}

{{- if $project.enabled }}
{{- range $component := $project.components }}
{{- $data := dict "project"           $project
                  "component"         $component
                  "environment"       $.Values.environment
                  "namespace"         $.Release.Namespace }}

# contains ssh key for component repo
{{ include "tekton-apps.service-account" (set (set $data "suffix" "build-pipeline-sa")           "secret" (include "tekton-apps.component-repo-deploy-key" $data)) }}
{{- if hasKey $project "kubernetesRepository" }}
# contains ssh key for kubernetes repo
{{ include "tekton-apps.service-account" (set (set $data "suffix" "build-pipeline-kustomize-sa") "secret" (include "tekton-apps.kubernetes-repo-deploy-key" $data)) }}
{{- end }}
# contains webhook secret
{{ include "tekton-apps.service-account" (set (set $data "suffix" "trigger-sa")                  "secret" (include "tekton-apps.component-repo-webhook-secret" $data)) }}

{{- end }} # range component
{{- end }} # if project.enabled
{{- end }} # range
{{- end }} # if apps
