# Default values for tekton.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- This is required name of the hosted zone.
# All public services would be created under this hosted zone
domainZone: "site.com"

# If you want solution to pull images using a specific docker registry
# credentials:
#
# https://github.com/tektoncd/pipeline/blob/main/docs/podtemplates.md
# if you need to create dockerhub secrets you can follow the example below
#
# kubectl create secret -n argo-cd generic docker-saritasa-infra-v2-ro \
#     --from-file=.dockerconfigjson=$HOME/.docker/config.json \
#     --type=kubernetes.io/dockerconfigjson
#

engine:
  enabled: true

  # -- controller launch arguments
  # @default -- use args multiline string to set additional launch arguments for the tekton controller
  controller:
    args: |
      performance considerations
      uncomment 3 lines below if you need it
      https://github.com/tektoncd/pipeline/blob/main/docs/tekton-controller-performance-configuration.md
      "-kube-api-qps", "5",
      "-kube-api-burst", "10",
      "-threads-per-controller", "20",

  # -- tekton-defaults configuration which will be added into tekton-pipelines/config-defaults configmap
  config:
    # defaultServiceAccountcontains the default service account name
    # to use for TaskRun and PipelineRun, if none is specified.
    defaultServiceAccount: "build-bot-sa"
    #
    # defaultTimeoutMinutes contains the default number of
    # minutes to use for TaskRun and PipelineRun, if none is specified.
    defaultTimeoutMinutes: "60"
    #
    # defaultPodTemplate contains the default pod template to use for
    # TaskRun and PipelineRun. If a pod template is specified on the
    # PipelineRun, the default-pod-template is merged with that one.
    # defaultPodTemplate: |
    #   imagePullSecrets:
    #     - name: "docker-saritasa-infra-v2-ro"
    #   nodeSelector:
    #     ci: "true"
    #
    # defaultAffinityAssistantPodTemplate contains the default pod template
    # to use for affinity assistant pods. If a pod template is specified on the
    # PipelineRun, the default-affinity-assistant-pod-template is merged with
    # that one.
    # defaultAffinityAssistantPodTemplate: |
    #   nodeSelector:
    #     ci: "true"
    #
    # defaultCloudEventsSinkUrl contains the default CloudEvents sink to be
    # used for TaskRun and PipelineRun, when no sink is specified.
    # Note that right now it is still not possible to set a PipelineRun or
    # TaskRun specific sink, so the default is the only option available.
    # If no sink is specified, no CloudEvent is generated
    # defaultCloudEventsSinkUrl: "https://sink.domain.com"
    #
    # defaultMaxMatrixCombinationsCount contains the default maximum number
    # of combinations from a Matrix, if none is specified.
    # see: https://tekton.dev/docs/pipelines/matrix/
    # defaultMaxMatrixCombinationsCount: "256"
    #
    # defaultTaskRunWorkspaceBinding contains the default workspace
    # configuration provided for any Workspaces that a Task declares
    # but that a TaskRun does not explicitly provide.
    # defaultTaskRunWorkspaceBinding: |
    #   emptyDir: {}
    #

  # -- tekton config-artifact-pvc configuration
  storage:
    defaultPVCSize: 5Gi
    storageClassName: gp3

  # -- tekton enabled feature flags
  featureFlags:
    # Setting this flag to "true" will prevent Tekton to create an
    # Affinity Assistant for every TaskRun sharing a PVC workspace
    #
    # The default behaviour is for Tekton to create Affinity Assistants
    #
    # See more in the workspace documentation about Affinity Assistant
    # https://github.com/tektoncd/pipeline/blob/main/docs/workspaces.md#affinity-assistant-and-specifying-workspace-order-in-a-pipeline
    # or https://github.com/tektoncd/pipeline/pull/2630 for more info.
    disable-affinity-assistant: "false"
    # Setting this flag to "true" will prevent Tekton scanning attached
    # service accounts and injecting any credentials it finds into your
    # Steps.
    #
    # The default behaviour currently is for Tekton to search service
    # accounts for secrets matching a specified format and automatically
    # mount those into your Steps.
    #
    # Note: setting this to "true" will prevent PipelineResources from
    # working.
    #
    # See https://github.com/tektoncd/pipeline/issues/2791 for more
    # info.
    disable-creds-init: "false"
    # Setting this flag to "false" will stop Tekton from waiting for a
    # TaskRun's sidecar containers to be running before starting the first
    # step. This will allow Tasks to be run in environments that don't
    # support the DownwardAPI volume type, but may lead to unintended
    # behaviour if sidecars are used.
    #
    # See https://github.com/tektoncd/pipeline/issues/4937 for more info.
    await-sidecar-readiness: "true"
    # This option should be set to false when Pipelines is running in a
    # cluster that does not use injected sidecars such as Istio. Setting
    # it to false should decrease the time it takes for a TaskRun to start
    # running. For clusters that use injected sidecars, setting this
    # option to false can lead to unexpected behavior.
    #
    # See https://github.com/tektoncd/pipeline/issues/2080 for more info.
    running-in-environment-with-injected-sidecars: "true"
    # Setting this flag to "true" will require that any Git SSH Secret
    # offered to Tekton must have known_hosts included.
    #
    # See https://github.com/tektoncd/pipeline/issues/2981 for more
    # info.
    require-git-ssh-secret-known-hosts: "false"
    # Setting this flag to "true" enables the use of Tekton OCI bundle.
    # This is an experimental feature and thus should still be considered
    # an alpha feature.
    enable-tekton-oci-bundles: "false"
    # Setting this flag will determine which gated features are enabled.
    # Acceptable values are "stable", "beta", or "alpha".
    enable-api-fields: "stable"
    # Setting this flag to "true" enables CloudEvents for CustomRuns and Runs, as long as a
    # CloudEvents sink is configured in the config-defaults config map
    send-cloudevents-for-runs: "false"
    # Setting this flag to "enforce" will enforce verification of tasks/pipeline. Failing to verify
    # will fail the taskrun/pipelinerun. "warn" will only log the err message and "skip"
    # will skip the whole verification
    resource-verification-mode: "skip"
    # Setting this flag to "true" enables populating the "provenance" field in TaskRun
    # and PipelineRun status. This field contains metadata about resources used
    # in the TaskRun/PipelineRun such as the source from where a remote Task/Pipeline
    # definition was fetched.
    enable-provenance-in-status: "false"
    # Setting this flag to "full" to enable full embedding of `TaskRun` and `Run` statuses in the
    # `PipelineRun` status. Set it to "minimal" to populate the `ChildReferences` field in the
    # `PipelineRun` status with name, kind, and API version information for each `TaskRun` and
    # `Run` in the `PipelineRun` instead. Set it to "both" to do both.
    embedded-status: "minimal"
    # Setting this flag will determine the version for custom tasks created by PipelineRuns.
    # Acceptable values are "v1beta1" and "v1alpha1".
    # The default is "v1beta1".
    custom-task-version: "v1beta1"

  # -- tekton prometheus metrics observability configuration
  metrics:
    # metrics.backend-destination field specifies the system metrics destination.
    # It supports either prometheus (the default) or stackdriver.
    # Note: Using Stackdriver will incur additional charges.
    metrics.backend-destination: prometheus
    # metrics.request-metrics-backend-destination specifies the request metrics
    # destination. If non-empty, it enables queue proxy to send request metrics.
    # Currently supported values: prometheus, stackdriver.
    metrics.request-metrics-backend-destination: prometheus

    # metrics.stackdriver-project-id field specifies the Stackdriver project ID. This
    # field is optional. When running on GCE, application default credentials will be
    # used and metrics will be sent to the cluster's project if this field is
    # not provided.
    # metrics.stackdriver-project-id: "<your stackdriver project id>"

    # metrics.allow-stackdriver-custom-metrics indicates whether it is allowed
    # to send metrics to Stackdriver using "global" resource type and custom
    # metric type. Setting this flag to "true" could cause extra Stackdriver
    # charge.  If metrics.backend-destination is not Stackdriver, this is
    # ignored.
    metrics.allow-stackdriver-custom-metrics: "false"
    metrics.taskrun.level: "task"
    metrics.taskrun.duration-type: "histogram"
    metrics.pipelinerun.level: "pipeline"
    metrics.pipelinerun.duration-type: "histogram"


triggers:

dashboard:
  # -- tekton ingress configuration

    # annotations:
    #   kubernetes.io/ingress.class: "nginx"
    #   nginx.ingress.kubernetes.io/proxy-body-size: 100m
    #   cert-manager.io/cluster-issuer: "letsencrypt-prod"
    #   nginx.ingress.kubernetes.io/auth-type: basic
    #   nginx.ingress.kubernetes.io/auth-secret: tekton-basic-auth
    #   nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    #   argocd.argoproj.io/sync-wave: "1"
    # hosts:
    #   - host: tekton.site.com
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         backend:
    #           service:
    #             name: tekton-dashboard
    #             port:
    #               number: 9097
    # tls:
    #  - secretName: tekton.site.com-crt
    #    hosts:
    #      - tekton.site.com

webhook:
  # -- namespace where this webhook should be installed
  namespace: "ci"
  # -- webhook ingress configuration

    # annotations:
    #   kubernetes.io/ingress.class: "nginx"
    #   nginx.ingress.kubernetes.io/proxy-body-size: 100m
    #   cert-manager.io/cluster-issuer: "letsencrypt-prod"
    #   argocd.argoproj.io/sync-wave: "10"
    # hosts:
    #   - host: webhook.site.com
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         backend:
    #           service:
    #             name: el-build-pipeline-event-listener
    #             port:
    #               number: 8080
    # tls:
    #  - secretName: webhook.site.com-crt
    #    hosts:
    #      - webhook.site.com

# -- list of docker registry secrets to pull images
imagePullSecrets: []
# - name: "docker-saritasa-infra-v2-ro"

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "build-bot-sa"

# -- what node to run tekton related pods
nodeSelector: {}
#  tekton_builder: "true"

# -- tolerations for tekton related pods
tolerations: []

# -- affinity for tekton-related pods
# @default -- default is to avoid running tekton pods on windows nodes.
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: NotIn
              values:
                - windows
