apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-xrstf-github-exporter.fullname" . }}
  labels:
    {{- include "prometheus-xrstf-github-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "prometheus-xrstf-github-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "prometheus-xrstf-github-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9162
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            periodSeconds: 30
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          args:
            # address and port to listen on:
            - -listen=0.0.0.0:9162
            # use usernames instead of internal IDs for author labels
            - -realnames
            # max number of issues to fetch per repository (0 disables issues fetching)
            - -issue-depth=0
            # max number of milestones to fetch per repository (0 disables milestones fetching)
            - -milestone-depth=0
            {{- toYaml .Values.args | nindent 12 }}

          env:
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.existingSecret }}
                key: token

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
