---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.client }}-{{ .Values.environment }}-utils-role
  {{- if $.Values.namespace }}
  namespace: {{ $.Values.namespace }}
  {{- end }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/portforward", "pods/exec"]
    verbs: ["create"]

{{ if (.Values.rbac).client }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.client }}:view
  {{- if $.Values.namespace }}
  namespace: {{ $.Values.namespace }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.client }}-{{ .Values.environment }}-utils-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ .Values.client }}:view

{{ end }}
{{ if (.Values.rbac).developers }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: saritasa:sso:developers
  {{- if $.Values.namespace }}
  namespace: {{ $.Values.namespace }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.client }}-{{ .Values.environment }}-utils-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: saritasa:sso:developers
{{ end }}
