{{ if .Values.rbac.developers }}

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: saritasa-developers-readonly-clusterrole
rules:
  - apiGroups: [""]
    resources: ["nodes", "namespaces", "services", "pods", "persistentvolumes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions", "batch"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["tekton.dev"]
    resources: ["taskruns", "pipelineruns", "pipelines", "tasks"]
    verbs: ["get", "list", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: saritasa:sso:developers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: saritasa-developers-readonly-clusterrole
subjects:
# this group is creating when sso stack applied in infra-v3 and when saritasa-sso module applied in infra-v2
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: saritasa:sso:developers
# this group is coming from keycloak sso via oidc
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: developer

{{ end }}
