{{ if .Values.rbac.devops }}

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: saritasa:devops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
# this group is creating when sso stack applied in infra-v3 and when saritasa-sso module applied in infra-v2
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: saritasa-devops
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: saritasa-sso-devops
# this group is coming from keycloak sso via oidc
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: administrator
{{ end }}
