{{- range $pipeline := .Values.buildpacks.generate }}
{{$data := dict "pipeline"        $pipeline
                "namespace"       $.Release.Namespace
                "podTemplate"     $.Values.podTemplate
                "imagePullPolicy" $.Values.imagePullPolicy }}
{{ if and $.Values.buildpacks.enabled $pipeline.enabled }}
{{ include "trigger-template.buildpack" $data }}
{{ end }}
{{- end}}
