{{ if .Values.sentry.enabled }}
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sentry-release
  namespace: {{ .Release.Namespace }}

spec:
  description: >-
    The task prepares and deploys sentry release for projects, which exist in Sentry.

  workspaces:
    - name: source

  params:

    - name: sentry_project_name
      type: string
      description: name of the project in Sentry

    - name: environment
      type: string
      description: environment name of the app being built, i.e. dev/staging/prod

    - name: sourcemaps_dir
      type: string
      description: name of the dir where frontend sourcemaps would be stored in workspace
      default: "sourcemaps"

  stepTemplate:
    env:
      - name: SENTRY_AUTH_TOKEN
        valueFrom:
          secretKeyRef:
            name: {{ .Values.sentry.authTokenSecret }}
            key: {{ .Values.sentry.authTokenSecretKey }}
      - name: SENTRY_ORG
        value: {{ .Values.sentry.org }}
      - name: SENTRY_URL
        value: {{ .Values.sentry.url }}

  steps:
    - name: release
      image: {{ .Values.images.sentry_cli }}
      imagePullPolicy: {{ .Values.imagePullPolicy }}
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        set +x

        PROJECT_NAME="$(params.sentry_project_name)"
        PROJECT=$(sentry-cli projects list | awk -v col=4 '{print $col}' | grep ^${PROJECT_NAME}$)
        if [[ -z "${PROJECT}" ]]; then
          echo "Didn't find '${PROJECT_NAME}' project in Sentry. Skip this step."
          exit 0
        else
          echo "Found '${PROJECT_NAME}' project in Sentry, proceed with release."
        fi

        # sentry-cli uses last repository commit sha1 as proposed version, i.e. 7e734134fb23497e68976784f7eaa106c4a8f3a8
        # https://docs.sentry.io/product/cli/releases/#creating-releases
        VERSION=$(sentry-cli releases propose-version)

        sentry-cli releases new -p ${PROJECT_NAME} ${VERSION}
        sentry-cli releases set-commits --auto --ignore-missing -p ${PROJECT_NAME} ${VERSION}

        # needs to upload source maps for frontend projects from `/workspace/source/sourcemaps/` tekton build dir to Sentry,
        # they are generated and saved to `/workspace/source/sourcemaps/` dir at the end of `build-static` step
        if [[ -d "$(workspaces.source.path)/$(params.sourcemaps_dir)" ]]; then
          echo "Upload source maps for 'frontend' project"
          sentry-cli releases files -p ${PROJECT_NAME} ${VERSION} upload-sourcemaps $(workspaces.source.path)/$(params.sourcemaps_dir)
        else
          echo "That is not 'frontend' project, no source maps should be uploaded"
        fi

        sentry-cli releases deploys -p ${PROJECT_NAME} ${VERSION} new -e $(params.environment)

        # mark release as finalized and released, before this step it is marked as `unreleased`
        # https://docs.sentry.io/product/cli/releases/#finalizing-releases
        sentry-cli releases finalize -p ${PROJECT_NAME} ${VERSION}
{{ end }}
