{{- range $project := .Values.apps}}
{{ if $project.enabled }}
{{- range $component := $project.components }}

# initialize `projectEnvironment` variable with either `$project.environment` if it exists or with `$.Values.environment` otherwise
{{ $projectEnvironment := ternary $project.environment $.Values.environment (hasKey $project "environment") -}}

{{ $data := dict "project"     $project
                 "awsConf"     $.Values.aws
                 "slackConf"   $.Values.slack
                 "argocdConf"  $.Values.argocd }}

# ========================================================================
# 🌱 {{ $project.project | upper }}/{{ $component.name | upper }} COMPONENT BUILD PIPELINE CONFIG
# ========================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s-%s-build-pipeline-config" $project.project $component.name $projectEnvironment }}
  namespace: {{ $.Release.Namespace }}
  labels: {{ include "tekton-apps.labels" $ | nindent 4 }}

data:
  APPLICATION_URL: {{ $component.applicationURL }}
  MAIL_LIST: {{ include "tekton-apps.mailList" $data }}
  DEVOPS_GROUP_EMAIL: {{ include "tekton-apps.devopsMailList" $data }}
  JIRA_PROJECT_URL: {{ include "tekton-apps.jiraProjectURL" $data }}
  ARGOCD_SERVER: {{ $.Values.argocd.server }}
  ARGOCD_ROOT_PATH: {{ $.Values.argocd.rootPath | default "/" }}
  AWS_REGION: {{ $.Values.aws.region }}
  SLACK_CHANNEL: {{ include "tekton-apps.slackChannel" $data }}
  SLACK_FAILURE_ICON_URL: {{ $.Values.slack.imagesLocation | default "https://saritasa-rocks-ci.s3.us-west-2.amazonaws.com" }}/argocd-robot-sad.png
  SLACK_SUCCESS_ICON_URL: {{ $.Values.slack.imagesLocation | default "https://saritasa-rocks-ci.s3.us-west-2.amazonaws.com" }}/argocd-robot.png
  SLACK_FOOTER_ICON: {{ $.Values.slack.imagesLocation | default "https://saritasa-rocks-ci.s3.us-west-2.amazonaws.com" }}/k8s.png
  SLACK_FOOTER: Tekton
  TEKTON_PIPELINE_NAME: {{ $component.pipeline }}
  TEKTON_URL: {{ include "tekton-apps.tektonURL" $data }}
  {{- if $component.extraBuildConfigParams }}
  {{- toYaml $component.extraBuildConfigParams | nindent 2}}
  {{ end }}
---

{{- end }} # range component
{{- end }} # if project.enabled
{{- end }} # range project
