{{ if and .Values.aws.accessKeyId .Values.aws.secretAccessKey }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "terraform-pod.terraform-aws-iam-credentials" . }}
  labels:
    {{- include "terraform-pod.labels" . | nindent 4 }}
stringData:
  aws_access_key_id: {{ .Values.aws.accessKeyId }}
  aws_secret_access_key: {{ .Values.aws.secretAccessKey }}
  {{ if .Values.aws.sessionToken }}
  aws_session_token: {{ .Values.aws.sessionToken }}
  {{- end }}
{{ end }}
