apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "terraform-pod.git-crypt-key" . }}
  labels:
    {{- include "terraform-pod.labels" . | nindent 4 }}
data:
  git-crypt-key: {{ .Values.gitCryptKey }}
