{{ if and .Values.infracost.enabled  .Values.infracost.apiKey }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "terraform-pod.infracost-api-secret" . }}
  labels:
    {{- include "terraform-pod.labels" . | nindent 4 }}
stringData:
  token: {{ .Values.infracost.apiKey }}
{{ end }}
