{{ if .Values.terraform.token }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "terraform-pod.terraform-token" . }}
  labels:
    {{- include "terraform-pod.labels" . | nindent 4 }}
stringData:
  token: {{ .Values.terraform.token }}
{{ end }}
