name: Release Charts

on:
  push:
    branches:
      - main
      - feature/*
      - fix/*

jobs:
  release:
    name: Semantic Release
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3.5

      - name: Add saritasa repository dependency
        run: |
          helm repo add saritasa https://saritasa-nest.github.io/saritasa-devops-helm-charts/
          helm repo update

      - name: Semantic Release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v3.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            conventional-changelog-eslint@3.0.9
            semantic-release-helm3@2.3.3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          config: cr.yaml
          charts_dir: charts
          # uncomment when this PR is merged
          # https://github.com/helm/chart-releaser-action/pull/134/
          # skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
