name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    name: Lint & Test Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3.5

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml --chart-yaml-schema .ct/chart_schema.yaml --lint-conf .ct/lintconf.yaml --target-branch ${{ github.event.repository.default_branch }}
