apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: patch-argocd-application
  namespace: {{ .Release.Namespace }}
spec:
  description: Patch ArgoCD Application to update repositoryRevision parameter
  params:
    - name: application
      type: string
      description: ArgoCD Application name
    - name: repositoryRevision
      type: string
      description: Git branch/tag to deploy
  steps:
    - name: patch-application
      image: mikefarah/yq:4
      script: |
        #!/bin/sh
        set -e
        
        APPLICATION="$(params.application)"
        REVISION="$(params.repositoryRevision)"
        
        echo "Patching ArgoCD Application: $APPLICATION"
        echo "Setting repositoryRevision to: $REVISION"
        
        # Get current Application manifest
        kubectl get application "$APPLICATION" -n argo-cd -o yaml > /tmp/app.yaml
        
        # Update WP_GIT_REVISION value in initContainers env
        yq eval '(.spec.source.helm.values | from_yaml | .initContainers[0].env[] | select(.name == "WP_GIT_REVISION") | .value) = "'"$REVISION"'"' /tmp/app.yaml > /tmp/app-updated.yaml
        
        # Apply the updated manifest
        kubectl apply -f /tmp/app-updated.yaml
        
        echo "Application patched successfully"
