{{ if .Values.wordpress.enabled }}
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: wordpress-build-pipeline-trigger-template
  namespace: {{ .Release.Namespace }}
spec:
  params:
    {{ include "trigger-template.defaultParams" . | nindent 4 }}

    - name: kubernetes_namespace
      description: kubernetes namespace where wordpress is installed that requires POD redeployment

    - name: gitRevision
      description: git branch/tag to deploy

    - name: project
      description: project name (e.g., aaoa-staging)

    - name: component
      description: component name (e.g., wordpress)

  resourcetemplates:
  - kind: PipelineRun
    apiVersion: tekton.dev/v1beta1
    metadata:
      generateName: $(tt.params.application)-build-pipeline-run-
      labels:
        app: $(tt.params.application)
        project: $(tt.params.project)
        environment: $(tt.params.environment)
        component: $(tt.params.component)
    spec:
      serviceAccountName: $(tt.params.application)-build-pipeline-sa
      taskRunSpecs:
        - pipelineTaskName: git-clone-gitops-repository
          taskServiceAccountName: $(tt.params.application)-build-pipeline-kustomize-sa
        - pipelineTaskName: update-wordpress-kustomization
          taskServiceAccountName: $(tt.params.application)-build-pipeline-kustomize-sa
        - pipelineTaskName: update-values-yaml
          taskServiceAccountName: $(tt.params.application)-build-pipeline-kustomize-sa
      pipelineRef:
        name: wordpress-build-pipeline
      params:
        {{- include "pipeline.defaultTTBoundParams" (dict "kubernetes" true) | nindent 8 }}
        - name: kubernetes_namespace
          value: "$(tt.params.kubernetes_namespace)"
        - name: gitRevision
          value: "$(tt.params.gitRevision)"
        - name: project
          value: "$(tt.params.project)"
        - name: component
          value: "$(tt.params.component)"
      workspaces:
        {{- include "pipeline.defaultWorkspaces" . | nindent 8 }}
      podTemplate:
        volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
        {{- if .Values.podTemplate }}
        {{ toYaml .Values.podTemplate | nindent  8 }}
        {{end }}

{{ end }}
