{{ if .Values.wordpress.enabled }}
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: wordpress-build-pipeline-trigger-template
  namespace: {{ .Release.Namespace }}
spec:
  params:
    {{- include "params.app" (dict "target" "tt") | nindent 4 }}
    {{- include "params.git" (dict "target" "tt") | nindent 4 }}
    - name: kubernetes_namespace
      description: kubernetes namespace where wordpress is installed that requires POD redeployment

  resourcetemplates:
  - kind: PipelineRun
    apiVersion: tekton.dev/v1
    metadata:
      generateName: $(tt.params.application)-build-pipeline-run-
      labels:
        app: $(tt.params.application)
        project: $(tt.params.project)
        environment: $(tt.params.environment)
        component: $(tt.params.component)
    spec:
      pipelineRef:
        name: wordpress-build-pipeline
      params:
        {{- include "bonds.app" (dict "source" "tt") | nindent 8 }}
        {{- include "bonds.git" (dict "source" "tt") | nindent 8 }}
        - name: kubernetes_namespace
          value: "$(tt.params.kubernetes_namespace)"
      taskRunTemplate:
        serviceAccountName: $(tt.params.application)-build-pipeline-sa
        podTemplate:
          volumes:
          - name: podinfo
            downwardAPI:
              items:
                - path: "labels"
                  fieldRef:
                    fieldPath: metadata.labels
                - path: "annotations"
                  fieldRef:
                    fieldPath: metadata.annotations
          {{- if .Values.podTemplate }}
          {{ toYaml .Values.podTemplate | nindent  10 }}
          {{end }}

{{ end }}
